#!/bin/bash

echo
echo Starting Test 3: Building consensus with prevous prepare in the system
echo

# Startup
cd classes
rmiregistry 8123 &
RPMPID=$!
cd ..
sleep 1
java -classpath classes Server Paxos1 localhost Paxos2 localhost Paxos3 8123 &
PAXOS1=$!
java -classpath classes Server Paxos2 localhost Paxos1 localhost Paxos3 8123 &
PAXOS2=$!
java -classpath classes Server Paxos3 localhost Paxos1 localhost Paxos2 8123 &
PAXOS3=$!
sleep 1

# Competing proposer.  Start by sending a higher numbered prepare
java -classpath classes Client localhost Paxos2 8123 prepare 3 Paxos2

java -classpath classes Client localhost Paxos3 8123 prepare 3 Paxos2

# Now propose something else and see what we learn
java -classpath classes Client localhost Paxos1 8123 propose 123
java -classpath classes Client localhost Paxos3 8123 learn

#cleanup
kill $PAXOS1
kill $PAXOS2
kill $PAXOS3
kill $RPMPID
rm Paxos*.txt

