#!/bin/bash

echo
echo Starting Test 5: Competing Proposers
echo

# Startup
cd classes
rmiregistry 8123 &
RPMPID=$!
cd ..
sleep 1
java -classpath classes Server Paxos1 localhost Paxos2 localhost Paxos3 8123 &
PAXOS1=$!
java -classpath classes Server Paxos2 localhost Paxos1 localhost Paxos3 8123 &
PAXOS2=$!
java -classpath classes Server Paxos3 localhost Paxos1 localhost Paxos2 8123 &
PAXOS3=$!
sleep 1

# Competing proposer.  Start by sending a higher numbered prepare
java -classpath classes Client localhost Paxos2 8123 prepare 25 Paxos2

java -classpath classes Client localhost Paxos3 8123 prepare 25 Paxos2


# Now send two processes to prose different things at the same time
java -classpath classes Client localhost Paxos1 8123 propose 111 &
CLIENT1=$!
java -classpath classes Client localhost Paxos2 8123 propose 222 &
CLIENT2=$!

# Wait for both to finish
wait $CLIENT1 $CLIENT2

# Now check to see who won!
java -classpath classes Client localhost Paxos3 8123 learn


#cleanup
kill $PAXOS1
kill $PAXOS2
kill $PAXOS3
kill $RPMPID
rm Paxos*.txt

